### ISSUE TITLE
Unable to start server (CUDNN_STATUS_NOT_INITIALIZED)

### ISSUE THREAD

**Issue by fromeijn** [toverainc/willow-inference-server#108]
Just have a fresh install of Ubuntu (22.04.2) on my laptop with `NVIDIA GeForce GTX 1650 with Max-Q Design`. Tried to install the server following instructions in the readme ([c3340cc](https://github.com/toverainc/willow-inference-server/commit/c3340cc077f592a4e2ddd95312817b816e83ae23)). Using driver from NVIDIA nvidia-driver-525

When starting the sever i'm getting this message and sever will reboot over and over again (default settings)

```
willow-inference-server-wis-1    | [2023-07-21 15:29:23 +0000] [90] [INFO] Warming models...
willow-inference-server-wis-1    | [2023-07-21 15:29:24 +0000] [90] [DEBUG] WHISPER: Loading audio took 1231.369 ms
willow-inference-server-wis-1    | [2023-07-21 15:29:24 +0000] [90] [DEBUG] WHISPER: Feature extraction took 7.83 ms
willow-inference-server-wis-1    | [2023-07-21 15:29:24 +0000] [90] [DEBUG] WHISPER: Forcing language en
willow-inference-server-wis-1    | [2023-07-21 15:29:24 +0000] [90] [DEBUG] WHISPER: Using model tiny with beam size 1
willow-inference-server-wis-1    | [2023-07-21 15:29:24 +0000] [90] [ERROR] Traceback (most recent call last):
willow-inference-server-wis-1    |   File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 677, in lifespan
willow-inference-server-wis-1    |     async with self.lifespan_context(app) as maybe_state:
willow-inference-server-wis-1    |   File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 566, in __aenter__
willow-inference-server-wis-1    |     await self._router.startup()
willow-inference-server-wis-1    |   File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 656, in startup
willow-inference-server-wis-1    |     handler()
willow-inference-server-wis-1    |   File "/app/main.py", line 1058, in startup_event
willow-inference-server-wis-1    |     warm_models()
willow-inference-server-wis-1    |   File "/app/main.py", line 421, in warm_models
willow-inference-server-wis-1    |     do_whisper("client/3sec.flac", "tiny", beam_size, "transcribe", False, "en")
willow-inference-server-wis-1    |   File "/app/main.py", line 617, in do_whisper
willow-inference-server-wis-1    |     results = whisper_model.generate(features, [prompt]*batch_size, beam_size=beam_size, return_scores=False)
willow-inference-server-wis-1    | RuntimeError: cuDNN failed with status CUDNN_STATUS_NOT_INITIALIZED
willow-inference-server-wis-1    | 
willow-inference-server-wis-1    | 
willow-inference-server-wis-1    | [2023-07-21 15:29:24 +0000] [90] [ERROR] Application startup failed. Exiting.
willow-inference-server-wis-1    | [2023-07-21 15:29:24 +0000] [90] [INFO] Worker exiting (pid: 90)
willow-inference-server-wis-1    | [2023-07-21 15:29:25 +0000] [88] [INFO] Shutting down: Master
willow-inference-server-wis-1    | [2023-07-21 15:29:25 +0000] [88] [INFO] Reason: Worker failed to boot.
```
[full log here](https://github.com/toverainc/willow-inference-server/files/12130177/c3340cc-startup-log.log)

Not sure what to do how to solve this, reboot of the system doesn't help.

**Comment by nikito** [comment]
What's the output of nvidia-smi?

**Comment by fromeijn** [comment]
output of `nvidia-smi`
```
Fri Jul 21 17:50:52 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.125.06   Driver Version: 525.125.06   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:02:00.0 Off |                  N/A |
| N/A   32C    P3     5W /  30W |      6MiB /  4096MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1073      G   /usr/lib/xorg/Xorg                  4MiB |
+-----------------------------------------------------------------------------+
```

**Comment by nikito** [comment]
I think I see the problem. 4GB of VRam is a bit too low to run everything I think. 
Here's my output with WIS running and TTS enabled:
![image](https://github.com/toverainc/willow-inference-server/assets/733609/09b09c8e-5231-41a5-8c1f-665e0a8e0157)
As you can see I am already at 5.27GB. Now I had thought in the latest code it will disable TTS and such if you don't have enough VRAM, but even with that I am not sure if 4GB is enough, maybe @kristiankielhofner can answer to that? :)

**Comment by fromeijn** [comment]
Im able to run it without TTS, i copied settings with 
```
cp settings.py custom_settings.py
```
and set  TTS to false

```
support_tts: bool = False
```

afterwards it fits
```
Fri Jul 21 18:12:58 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.125.06   Driver Version: 525.125.06   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:02:00.0 Off |                  N/A |
| N/A   46C    P0    11W /  35W |   3362MiB /  4096MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1073      G   /usr/lib/xorg/Xorg                  4MiB |
|    0   N/A  N/A     26685      C   gunicorn: worker [main:app]      3354MiB |
+-----------------------------------------------------------------------------+
```

**Comment by fromeijn** [comment]
closing ticket
