### ISSUE TITLE
WIS returned HTTP error: 500

### ISSUE THREAD

**Issue by bert269** [toverainc/willow-inference-server#97]
Jsut setup the WIS and re-configure ESPBox-lite.
When I issue a voice command, this is the respose:
![image](https://github.com/toverainc/willow-inference-server/assets/18601216/748dda91-b0db-48b5-841b-de77e30f5f99)

during the config step, I used the WIS address in both places:
![image](https://github.com/toverainc/willow-inference-server/assets/18601216/a92f53ea-e739-4ee4-9551-f2b7caa0e0ba)

Is this correct, or should it only be for willow and not tts ?
Thanks

**Comment by bert269** [comment]
THis is the error log on WIS:
[2023-06-29 22:23:54 +0000] [80] [INFO] Willow Inference Server is starting... Please wait.
[2023-06-29 22:23:57 +0000] [80] [INFO] CUDA: Detected 1 device(s)
[2023-06-29 22:23:57 +0000] [80] [INFO] CUDA: Device 0 name: NVIDIA GeForce GTX 1080 Ti
[2023-06-29 22:23:57 +0000] [80] [INFO] CUDA: Device 0 capability: 61
[2023-06-29 22:23:57 +0000] [80] [INFO] CUDA: Device 0 total memory: 11711873024 bytes
[2023-06-29 22:23:57 +0000] [80] [INFO] CUDA: Device 0 free memory: 11564941312 bytes
[2023-06-29 22:23:57 +0000] [80] [WARNING] CUDA: Device 0 is pre-Turing, forcing int8
[2023-06-29 22:23:57 +0000] [80] [INFO] Started server process [80]
[2023-06-29 22:23:57 +0000] [80] [INFO] Waiting for application startup.
[2023-06-29 22:23:58 +0000] [80] [INFO] CTRANSLATE: Supported compute types for device cuda are {'float32', 'int8'} - using configured int8
[2023-06-29 22:23:58 +0000] [80] [INFO] Loading Whisper models...
[2023-06-29 22:24:12 +0000] [80] [INFO] Loading TTS models...
[2023-06-29 22:24:19 +0000] [80] [INFO] Warming models...
[2023-06-29 22:24:35 +0000] [80] [INFO] Willow Inference Server is ready for requests!
[2023-06-29 22:24:35 +0000] [80] [INFO] Application startup complete.
[2023-06-29 23:15:23 +0000] [80] [ERROR] Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/uvicorn/protocols/http/httptools_impl.py", line 436, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.8/dist-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/fastapi/applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.8/dist-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/local/lib/python3.8/dist-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/usr/local/lib/python3.8/dist-packages/fastapi/routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.8/dist-packages/fastapi/routing.py", line 163, in run_endpoint_function
    return await dependant.call(**values)
  File "/app/main.py", line 859, in willow
    language, results, infer_time, translation, infer_speedup, audio_duration = do_whisper(audio_file, model, beam_size, task, detect_language, return_language)
  File "/app/main.py", line 444, in do_whisper
    results = whisper_model.generate(features, [prompt]*batch_size, beam_size=beam_size, return_scores=False)
RuntimeError: cuDNN failed with status CUDNN_STATUS_INTERNAL_ERROR
[2023-06-29 23:21:50 +0000] [80] [ERROR] Exception in ASGI application

**Comment by bert269** [comment]
did a date set=time change on the server, resbooted and was able to connect.
Super fast response from ESPBOXes. Less than 450ms! WOW!

**Comment by kristiankielhofner** [comment]
Glad you got it figured out and are enjoying fast and accurate fully local and self-hosted voice!

A couple of tips if you want to play and tweak a few knobs:

- You can set the model used with URL parameters. The default is medium but if you want to make it faster you can try base:

`https://your_wis_host:19000/api/willow?model=base`

- Conversely, if you want highest quality with a reduction in speed you can try large:

`https://your_wis_host:19000/api/willow?model=large`

If you really want max accuracy you can crank up the beam size as well:

`https://your_wis_host:19000/api/willow?model=large&beam_size=5`

This will use the highest possible overall quality available with Whisper. With your GTX 1080 Ti you should still see sub 1s response times (but I can't be completely sure) even while giving it borderline ridiculously complex and specific voice commands.

Try it out and BTW - there are even more performance improvements, configuration options, and dramatic usability improvements coming with our pending first stable release across WIS and Willow. Stay tuned for that!
